name: AndroidBuild
on:
  pull_request:
    branches: [ main, develop, feature/* ]
  push:
    branches: [ main, develop, feature/* ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        api-level: [ 29, 30, 31, 32, 33, 34 ]
        target: [ app, core, testing ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew ${{ matrix.target }}:assembleDebug

      - name: Run unit tests
        run: ./gradlew ${{ matrix.target }}:testDebugUnitTest

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.3
        if: success()
        with:
          name: android-ci-cd.apk
          path: app/build/outputs/apk/app-debug.apk